package com.springdynamodbdemo.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "person")
public class Person implements Serializable{

	@DynamoDBHashKey(attributeName = "personId")
	@DynamoDBAutoGeneratedKey
	private String personId;
	
	@DynamoDBAttribute
	private String name;
	
	@DynamoDBAttribute
	private String email;
	
	@DynamoDBAttribute
	private int age;
	
	@DynamoDBAttribute
	private Address address;
	
}
